/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulpejemplo.vistas;

import java.awt.Color;

/**
 *
 * @author marti
 */
public class ULPvistas extends javax.swing.JFrame {

    /**
     * Creates new form ULPvistas
     */
    
    // Set the background color to green
    Color fondoColor = new Color(0, 153, 153);
    
    public ULPvistas() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPescritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMestudiante = new javax.swing.JMenu();
        jMIformEstud = new javax.swing.JMenuItem();
        jMmateria = new javax.swing.JMenu();
        jMIformuMateria = new javax.swing.JMenuItem();
        jMadministracion = new javax.swing.JMenu();
        jMIadminInscrip = new javax.swing.JMenuItem();
        jMIadminNotas = new javax.swing.JMenuItem();
        jMconsulta = new javax.swing.JMenu();
        jMIconsultEstPorMate = new javax.swing.JMenuItem();
        jMsalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDPescritorio.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jDPescritorioLayout = new javax.swing.GroupLayout(jDPescritorio);
        jDPescritorio.setLayout(jDPescritorioLayout);
        jDPescritorioLayout.setHorizontalGroup(
            jDPescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1318, Short.MAX_VALUE)
        );
        jDPescritorioLayout.setVerticalGroup(
            jDPescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1049, Short.MAX_VALUE)
        );

        jMestudiante.setText("Estudiante");
        jMestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMestudianteActionPerformed(evt);
            }
        });

        jMIformEstud.setText("Formulario de Estudiante");
        jMIformEstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIformEstudActionPerformed(evt);
            }
        });
        jMestudiante.add(jMIformEstud);

        jMenuBar1.add(jMestudiante);

        jMmateria.setText("Materia");

        jMIformuMateria.setText("Formulario de Materia");
        jMIformuMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIformuMateriaActionPerformed(evt);
            }
        });
        jMmateria.add(jMIformuMateria);

        jMenuBar1.add(jMmateria);

        jMadministracion.setText("Administración");

        jMIadminInscrip.setText("Gestionar Inscripciones");
        jMIadminInscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIadminInscripActionPerformed(evt);
            }
        });
        jMadministracion.add(jMIadminInscrip);

        jMIadminNotas.setText("Gestionar Notas");
        jMIadminNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIadminNotasActionPerformed(evt);
            }
        });
        jMadministracion.add(jMIadminNotas);

        jMenuBar1.add(jMadministracion);

        jMconsulta.setText("Consulta");

        jMIconsultEstPorMate.setText("Estudiantes por Materia");
        jMIconsultEstPorMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIconsultEstPorMateActionPerformed(evt);
            }
        });
        jMconsulta.add(jMIconsultEstPorMate);

        jMenuBar1.add(jMconsulta);

        jMsalir.setText("Salir");
        jMenuBar1.add(jMsalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPescritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPescritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMestudianteActionPerformed
        // TODO add your handling code here:
        //CANCEL THIS EVENT
    }//GEN-LAST:event_jMestudianteActionPerformed

    private void jMIformEstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIformEstudActionPerformed
        // TODO add your handling code here:
        jDPescritorio.removeAll();
        jDPescritorio.repaint();
        
        FormularioEstudiante fe = new FormularioEstudiante();
        fe.setVisible(true);
        jDPescritorio.add(fe);
        jDPescritorio.moveToFront(fe);
        
        // Set the background color to green
        fe.getContentPane().setBackground(fondoColor);
    }//GEN-LAST:event_jMIformEstudActionPerformed

    private void jMIformuMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIformuMateriaActionPerformed
        // TODO add your handling code here:
        jDPescritorio.removeAll();
        jDPescritorio.repaint();
        
        FormularioMaterias fm = new FormularioMaterias();
        fm.setVisible(true);
        jDPescritorio.add(fm);
        jDPescritorio.moveToFront(fm);
        // Set the background color to green
        fm.getContentPane().setBackground(fondoColor);
    }//GEN-LAST:event_jMIformuMateriaActionPerformed

    private void jMIadminInscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIadminInscripActionPerformed
        // TODO add your handling code here:
        jDPescritorio.removeAll();
        jDPescritorio.repaint();
        
        AdminInscrip ai = new AdminInscrip();
        ai.setVisible(true);
        jDPescritorio.add(ai);
        jDPescritorio.moveToFront(ai);
        // Set the background color to green
        ai.getContentPane().setBackground(fondoColor);
    }//GEN-LAST:event_jMIadminInscripActionPerformed

    private void jMIadminNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIadminNotasActionPerformed
        // TODO add your handling code here:
        jDPescritorio.removeAll();
        jDPescritorio.repaint();
        
        AdminNotas an = new AdminNotas();
        an.setVisible(true);
        jDPescritorio.add(an);
        jDPescritorio.moveToFront(an);
        // Set the background color to green
        an.getContentPane().setBackground(fondoColor);
    }//GEN-LAST:event_jMIadminNotasActionPerformed

    private void jMIconsultEstPorMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIconsultEstPorMateActionPerformed
        // TODO add your handling code here:
        jDPescritorio.removeAll();
        jDPescritorio.repaint();
        
        ConsulEstuMater cem = new ConsulEstuMater();
        cem.setVisible(true);
        jDPescritorio.add(cem);
        jDPescritorio.moveToFront(cem);
        // Set the background color to green
        cem.getContentPane().setBackground(fondoColor);
    }//GEN-LAST:event_jMIconsultEstPorMateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ULPvistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ULPvistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ULPvistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ULPvistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ULPvistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPescritorio;
    private javax.swing.JMenuItem jMIadminInscrip;
    private javax.swing.JMenuItem jMIadminNotas;
    private javax.swing.JMenuItem jMIconsultEstPorMate;
    private javax.swing.JMenuItem jMIformEstud;
    private javax.swing.JMenuItem jMIformuMateria;
    private javax.swing.JMenu jMadministracion;
    private javax.swing.JMenu jMconsulta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMestudiante;
    private javax.swing.JMenu jMmateria;
    private javax.swing.JMenu jMsalir;
    // End of variables declaration//GEN-END:variables
}
